apiVersion: v1
kind: Service
metadata:
  name: kubernetes-backend
spec:
  selector:
    app: kubernetes
  ports:
    - port: 80
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubecontainer
        image: agustingomezdev/backendcoderhouse:1.0.0
        ports:
          - containerPort: 9090
        env:
          - name: MONGO
            value: mongodb+srv://facumanta10:6VXFGaou1y8F4X8H@fmantabackend.tpf6egh.mongodb.net/miEcommerce
          - name: JWT_KEY
            value: "SecretCoderKey"
          - name: JWT_RESET_PASSWORD_KEY
            value: "d942738b"
          - name: JWT_COOKIE_KEY
            value: "jwtCookieToken"
          - name: GITHUB_CLIENT_ID
            value: "Iv1.4f85ef82f7e38ff0"
          - name: GITHUB_CLIENT_SECRET
            value: "b4382fbecb80648088ea370b3d7554b2485aca18"
          - name: GITHUB_CALLBACK_URL
            value: "http://localhost:8080/api/users/githubcallback"
          - name: ADMIN_EMAIL
            value: "adminCoderhouse@gmail.com"
          - name: ADMIN_PASSWORD
            value: "adminCoderhouse"
          - name: PERSISTENCE
            value: "MONGO"
          - name: NODEMAILER_GMAIL
            value: "backendmanta2023@gmail.com"
          - name: NODEMAILER_PASS
            value: "qdwocbcqdgndneai"
        imagePullPolicy: Always